-- Migration: Expand staff.role MySQL ENUM to support VC, PRINCIPAL, VICE_PRINCIPAL, DEAN, WARDEN, and SUPER_ADMIN
ALTER TABLE staff MODIFY COLUMN role ENUM('VC','PRINCIPAL','VICE_PRINCIPAL','DEAN','WARDEN','SUPER_ADMIN') NOT NULL;
